### ISSUE TITLE
get5_end_match_on_empty_server ends the match after changing the map after map veto (or any other reason)

### ISSUE THREAD

**Issue by amans-ingh** [splewis/get5#670] opened 2021-05-31 19:52 UTC
If cvar `get5_end_match_on_empty_server` is set to 0, the following bug occurs.

### Expected behavior
match is setup ---> map veto ---> all the maps are decided ---> server changes the map ---> players join respected teams ----> match map goes live

### Actual behavior
match is setup ---> map veto ---> maps are decided ---> server changes the map ---> match is unloaded

### Steps to reproduce
- Plugin version: 0.7.2
- Sourcemod version: 1.10
- Steps to reproduce (please be specific): set `get5_end_match_on_empty_server` to 0 in `csgo/cfg/sourcemod/get5.cfg` ---> Load a match from file or url ---> all players join ---> server map changes automatically ---> match unloaded

**Comment by lugaamn** [comment] 2022-06-15 06:12
yes

**Comment by PhlexPlexico** [comment] 2022-06-22 17:33
Hey, 

Sorry it's been quite a while since this was reported, but I believe this was on a dev version of 0.7.2 at the time. Would you mind trying with a more recent [build](https://github.com/splewis/get5/suites/6066818841/artifacts/209638473) and see if its still causing this issue?

Thanks!

**Comment by PhlexPlexico** [comment] 2022-06-22 19:17
Also, this appears to be a duplicate of https://github.com/splewis/get5/issues/355 - will close, and if you can reproduce with the latest build, please comment in there. Thanks!

**Closed by PhlexPlexico** 2022-06-22 19:17 UTC
