### ISSUE TITLE
get5_last_backup_file not working?

### ISSUE THREAD

**Issue by AdrianMrn** [splewis/get5#83] opened 2016-11-02 15:59 UTC
### Expected behavior
When using get5_last_backup_file after a server crash/restart I expected to get the filename of the last backup file.

### Actual behavior
The get5_last_backup_file convar is empty and I have to figure out manually what the last backup file is.

### Steps to reproduce
- Plugin version: latest
- Sourcemod version: latest
- I'm using the get5_scrim config.

**Comment by Technoblazed** [comment] 2016-11-02 16:02
If your server is crashing on its own, with just a scrim plugin on it, I'd look into the cause of the actual crash as well as this.

**Comment by AdrianMrn** [comment] 2016-11-02 16:05
It's not, I'm just simulating crashes to make sure I won't run into any unexpected situations during a game.

**Comment by Technoblazed** [comment] 2016-11-02 16:15
The webpanel is always a viable option o.o

**Comment by AdrianMrn** [comment] 2016-11-02 16:16
Yeah I thought about using that but I'm not running the LAN myself. The guy who's running it wants as little configuration between matches as possible.

**Comment by splewis** [comment] 2016-11-03 03:34
The cvar gets updated when backup files are written, that's all it promises - not also restoring on a server restart, so this is working as intended.

**Comment by splewis** [comment] 2016-11-15 06:56
I'm closing this as expected behavior. I don't think the cvar should be reset on startup.

**Closed by splewis** 2016-11-15 06:56 UTC
