### ISSUE TITLE
get5_max_pause_time does not work correctly

### ISSUE THREAD

**Issue by boXseven** [splewis/get5#191] opened 2017-10-09 22:45 UTC
### Expected behavior
get5_max_pause_time "0" = unlimited pause time
- With version 0.5.2 it worked.

### Actual behavior
get5_max_pause_time "0" = 0 seconds pause time
- That's why I changed it to 9999 seconds.

### Steps to reproduce
Set get5_max_pause_time to "0"

### get5_debuginfo
https://pastebin.com/raw/4dsszBDC

- Plugin version: 0.5.3
- Sourcemod version: 1.8.0.5998

**Comment by splewis** [comment] 2017-10-14 23:30
I wasn't able to reproduce this. Can you check to see if it's still present on build 334: https://ci.splewis.net/job/get5/354/

**Comment by gabrielfgularte** [comment] 2017-10-23 14:44
@boXseven This should be already fixed in 549731d. Could you check if the latest build is working as expected? You can download it here: https://ci.splewis.net/job/get5/lastSuccessfulBuild/artifact/builds/get5/get5-357.zip.

**Comment by splewis** [comment] 2017-11-05 23:07
> I updated the util.sp, but it didn't work.

Because updating the source code won't do anything if you don't recompile.

**Comment by gabrielfgularte** [comment] 2017-11-06 13:29
@boXseven You have to compile your sourcecode. I have a repo that soon will be able to compile any sourcemod (or the most of them), but for now is compiling get5 very well. If you use Docker, maybe it can be useful for you. https://github.com/gabrielfgularte/sourcemod-compiler

**Comment by splewis** [comment] 2017-12-02 05:31
There's no update here, and I believe it's fixed, so I'm closing it. If it's not fixed feel free for anyone to reopen.

**Closed by splewis** 2017-12-02 05:31 UTC
Labels: bug
