### ISSUE TITLE
Technical Pause not working

### ISSUE THREAD

**Issue by CanExiOne** [splewis/get5#479] opened 2020-03-24 22:22 UTC
### Expected behavior

Start technical pause after both teams type !tech in chat

### Actual behavior

Nothing happens

### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version: 0.7.1
- Sourcemod version: 1.10.0.6462
- Steps to reproduce (please be specific): Use !tech on both sides after starting match.

**Comment by splewis** [comment] 2020-03-26 04:07
Any error logs? https://github.com/splewis/get5/wiki/Debugging-help#getting-error-logs

**Comment by zeratulhx** [comment] 2020-03-26 08:54
`L 03/26/2020 - 16:51:42: [get5] get5_event: {"matchid`":"example_match","params":{"client":"PikeZz<2><STEAM_1:0:1703467><>","map_number":0,"map_name":"de_nuke","message":"!tech"},"event":"client_say"}`
That's everything

**Comment by CanExiOne** [comment] 2020-03-26 11:15
> 
> 
> Any error logs? https://github.com/splewis/get5/wiki/Debugging-help#getting-error-logs

Sorry I forgot to include those, here they are.

[get5_debug.log](https://github.com/splewis/get5/files/4386792/get5_debug.log)

**Comment by hpksoldati** [comment] 2020-04-13 18:56
same problem here, in windows and linux servers

**Comment by TandelK** [comment] 2020-04-14 08:21
@hpksoldati @CanExiOne The issue is because it was fix after Release version of 0.7.1 . You will have to manually download the Release or use Travis Build . For latest travis build you can find it on 
`https://ci.splewis.net/job/get5/lastSuccessfulBuild/artifact/builds/get5/get5-481.zip`

**Comment by splewis** [comment] 2020-04-16 02:19
Yes, you need a build that includes https://github.com/splewis/get5/commit/1523e010e1e812fcd31552d2b02e0c4470c2a414, which you could get from https://ci.splewis.net/job/get5/lastSuccessfulBuild/.

I intend to make a new official release in the next week or so, though.

**Comment by hpksoldati** [comment] 2020-04-20 20:09
Solved here big thanks. 
I'm using it for a league, and we use a custom hud, the tactical pause counter doesn't work, any chance for the plugin to execute the command timeout_ct_start and timeout_terrorist_start?

**Comment by TandelK** [comment] 2020-04-20 20:24
It has own Pause system inbuilt. It has both systems of Pauses and even cvar to reset pauses in each half

1. Max Pauses with Fix Time -- You can call it similar to Timeout  
eg. 30 Seconds per pauses. With this no one can un-pause the game and it will be fixed time. This does not use Max Pause time cvar.
2. Max Pause Time with unlimited usage - 
Eg. 300 seconds defined. A Team can use random pauses time of maximum 300 seconds that can be anytime during the match . One pause can be 1 minute and second one can be 4 minute but cannot take more as 5 minutes will be over 

Both will trigger with Reset Pauses on each half if cvar is enabled.

**Comment by hpksoldati** [comment] 2020-04-24 15:06
Thanks again.

What I mean is that if the plugin executes the command timeout_ct_start or t. He will also use the game counter.

Sort of like this: 

public Action:Command_Tech(client, args) {
    if (IsPaused() || !IsValidClient(client))
        return Plugin_Handled;
		
	new team = GetClientTeam(client);	

    if (team == CS_TEAM_T) {
	    ServerCommand("timeout_terrorist_start");
		PrintToChatAll(" \x02Terrorists has requested a tactical pause.");
	} else if (team == CS_TEAM_CT)  {
	    ServerCommand("timeout_ct_start");
	    PrintToChatAll(" \x0CCounter-Terrorists has requested a tactical pause."); 
	}
	
    return Plugin_Handled;
}

It gets confusing for those watching or broadcasting ...

![Example](https://user-images.githubusercontent.com/16945944/80227291-ced0f700-8623-11ea-97e2-de15f9c9d659.png)

sorry for this bic picture and my bad english.

Thanks

**Comment by splewis** [comment] 2020-04-25 06:30
> What I mean is that if the plugin executes the command timeout_ct_start or t. He will also use the game counter.

Yes, the plugin could do that. Pull requests welcome. Any added functionality needs to fit into the existing pausing system, though.

**Closed** 2021-07-17 20:21 UTC
Labels: user help
