### ISSUE TITLE
[BUG] First round restore swap issues

### ISSUE THREAD

**Issue by TandelK** [splewis/get5#699] opened 2021-09-05 12:13 UTC
### Expected behavior
When using stop command on the very first Round for Technical reasons and restoring round00.cfg backup file it should just reset the round itself properly back to their teams. 

### Actual behavior
When Using backup00.cfg with the team which has swapped after knife  for side selection, it resets the  sides again to their old team.

### Steps to reproduce
Plugin version: 0.7.3-dev
Sourcemod Version = 1.10.0.6509

Steps to reproduce 
1)  Create Match with Knife for Side Selection
2) Start Knife round and then swap the sides. 
3) In first round use the stop  command and check the  side of the team that swapped has been resetted.

**Comment by TandelK** [comment] 2021-09-06 16:38
@splewis Does the Round Restore actually use Official Valve Backup ? If so it is not getting updated after the teams have been swap. I checked the backup created by get5 which actually while creating first time does properly stores the Team Swaps but as soon as we load the backup of round00 it seems that it is getting swapped because it might be using Valve Official backup and it does not seems to have updated after Knife Round.

**Comment by arildboifot** [comment] 2021-09-21 18:26
Might be related to #652 ?

**Comment by PhlexPlexico** [comment] 2022-05-14 20:48
Okay, so I think I'm going to use this issue to consolidate a few bugs in relation to the backup system if that's alright. And some possible solutions/patches that can be made here.

### Side Restore Issues

@TandelK had sent me some backup files to help debug this situation in this ticket. I believe that every pre-round start, the backup system writes a backup file, as seen here - 
https://github.com/splewis/get5/blob/5afc25b5f27e2bae923c2e47e3cfbc901259bbc6/scripting/get5.sp#L1150-L1166

However, when the knife round ends this function I believe technically runs in while we're still selecting sides, and the teams are still in their initial configuration that was sent to the match server. So, when a team calls `!swap`, the prelive value is still set to `team1` being on `team1_side` and `team2` being on `team2_side`. We can see that during the `PerformSideSwap` call, we don't call any updates to the backup structure. This can be seen in this call, that no calls to writing the backup is performed.

https://github.com/splewis/get5/blob/5afc25b5f27e2bae923c2e47e3cfbc901259bbc6/scripting/get5/kniferounds.sp#L26

Since there is no round end when selecting either `!stay` or `!swap`, the backup structure still has the defaults from how the match was setup, which I believe causes this match restore issue. So I think there's two ways of possibly fixing this one issue. One is when we swap the teams, have it restart the game with sides swapped so that the prelive config updates to set the `team1_side` and `team2_side` in the backup structure properly, or just call a write to the backup structure in the above call when we perform a side swap. I think I like the latter better as it avoids having to do any janky round-end shenanigans on it.

If TandelK is okay with it, I will also upload those backups to this ticket so we can get additional observation on both the Valve backups, and the get5 backups, but I do believe we just need to do a simple write to the backup structure on swapping sides, before the state changes.

### Coach Issues
This one was reported to me personally, and I may be requesting some more information and at least a reproducible example (GoTV, Video, or otherwise), but it appears there was an issue with restoring coaches, which I think may be in relation to #700. When a match restore was called, the coaches in the match was unable to join back into the coach slot. I will await some more information for this as well.


### Pause/Unpause Issue
This one was reported in the Discord, and we're still looking into a possible, reproducible way for this. I'm not sure if PR #749 has anything to do with this, as the user had mentioned previously that it had happened a few times without the new feature. Essentially when the two teams agreed to stop and restore the match to the last round using `.stop`, they were unable to resume the game with `.unpause` and the only way the match could resume is if an admin used rcon to call `sm_unpause`. We're waiting for more information on this one as well, but I'll be actively looking into this one as well as I verify the tech pause changes are working as intended, as I was unable to reproduce it after testing a few times.


I'll edit this comment as well with more information as I come across it, and if time permits but I hope this may help someone else who may want to take a look into resolving these issues :) if you think these issues should be spread out into three separate tickets (and link/close all other issues relating to it), just let me know!

**Comment by TandelK** [comment] 2022-05-16 18:23
@PhlexPlexico You can surely share the Files here and we can work on fixing this major issues.

**Comment by PhlexPlexico** [comment] 2022-05-16 18:26
[Backup.zip](https://github.com/splewis/get5/files/8702476/Backup.zip)

Attached are the match backups that show this behaviour. After I can fix a potential issue with the .stop command I'll see if I can find a way to fix these issues as well.

Thanks!

**Closed** 2022-06-26 22:16 UTC
