### ISSUE TITLE
Bug? Player gets assigned to Spectator-team upon reconnect rather than T/CT until next round starts.

### ISSUE THREAD

**Issue by DtN1337** [splewis/get5#268] opened 2018-06-22 10:02 UTC
### Expected behavior
When a player disconnects and reconnects to the server, they should be assigned to the correct team when spam-clicking the SPACE-button. As far as I know, if this is during the freezetime or early-round, the player would correctly be assigned to a team and spawn. However, if it's too late in the round to spawn, the player would instead be put in the Spectator-team.

### Actual behavior
Instead of being assigned to the team the player is locked onto by SteamID through the configuration file, they would be put on the Spectator-team while being DEAD. Upon next round start, the player gets moved correctly to either T/CT side.

### Steps to reproduce
- Plugin version: 0.5.5 - although this is not the latest version, I don't believe the issue is resolved in the latest version, based on the update notes.
- Sourcemod version: 1.8.0.6022
- Steps to reproduce (please be specific):

When a player disconnected from the server (for whatever reason), reconnects again and spam clicks the SPACE-button to join the team the player is locked to, this bug occurs in some cases. At first I thought it was very rare, but I experienced it more and more often when having a match live and someone would disconnect/reconnect.

Instead of getting locked to the expected team, they are locked onto the Spectator-team, being able to watch the entire game live, knowing all enemy positions etc. Once the round is over, the player would automatically be moved to the correct team again.

I have tried forcing mp_spectators_max to 0, but this still occurs.

**Comment by Technoblazed** [comment] 2018-06-22 11:11
This is a limitation of the game but it’s pretty much intentional and the best fix.

**Comment by dtnlol** [comment] 2018-06-22 11:14
What sort of limitations? It's a bit problematic if it's exposed and more people would take advantage of it during matches. Pretty dumb, I know - but some people are just like that.

**Comment by splewis** [comment] 2018-06-23 04:17
> This is a limitation of the game but it’s pretty much intentional and the best fix. \

I have no idea what that means.

Team locking in general is a pain (see also https://github.com/splewis/get5/issues/1, https://github.com/splewis/get5/issues/216). This issue should be fixable, but unfortunately it takes a lot of experimentation with the commands & events to get right. That said, I'm pretty confident this should be considered a get5 bug since there are real examples of team locking working well (Faceit for example).

Ideally Valve adds a team-locking mechanims similar to how player names can be forced, but that's unlikely to happen :(

Thanks for the clear bug report.

**Comment by keeradfun** [comment] 2018-08-27 10:16
Actually there is more to this bug.
As an admin where i have to manage multiple matches, i will be leaving a game and join other game and when i join back to the game which i left earlier i will be placed in CT side instead of spectator. I had to join spectator manually.

1) This issue happened to me only after halftime never happened to me in the first half.
2) Most the time this happened when the game was 4-5 rounds away from finishing.
3) Always whenever this bug happens i would be placed in CT side.

**Comment by nickdnk** [comment] 2022-07-12 01:57
This is super old and I haven't ever experienced this on the newer builds. Closing. Reopen if you can reliably reproduce.

**Closed by nickdnk** 2022-07-12 01:57 UTC
Labels: bug
