### ISSUE TITLE
[Forfeit Issue]  Reference from get5-web

### ISSUE THREAD

**Issue by TandelK** [splewis/get5#395] opened 2019-05-22 14:25 UTC
I have listed the bug that was via get5 actually forgot to reference it here.  https://github.com/splewis/get5-web/issues/152

**Comment by TandelK** [comment] 2019-05-22 14:27
@splewis this is actually get5 bug and not get5-web bug as the Forfeit update is actually sent by get5 plugin.

**Comment by splewis** [comment] 2019-05-23 01:38
As always, step to reproduce & version info are pretty much required.

**Comment by TandelK** [comment] 2019-05-25 07:32
Understanding the issue step by step
`CVAR get5_time_to_start 600 `
Auto Forfeit if not shown up in 10 mins from the match created time.

**Only 1 Team Shows up**
1) Created a match between 2 teams  
2) Team 1 joins but team 2 does not shows up and after 10 minutes the message is sent to server that match is forfeited as team 2 did not show up or start the match. 
3) Database action - as match did not start the value of Start_Time is not updated and set to `NULL` by default and not updated and the condition checking of auto forfeit time that is 10 mins it will send Database update End Time as 10 minutes from the joining and ready time of Team 1 . 
4) Forfeit column gets updated to team id of team 2 for not showing up making team 1 as winner. 

Issues here : 
Panel does not get updated status of forfeit even the database has set the value of team 2 in forfeit column. It will still show match as pending as the START_TIME is still Null which leads to showing status of Pending on Panel 

**Both Teams not joined in given time or started match**
1) Created a match between team 1  and team 2
2) Its been 10 minutes and no teams have ready up or joined the match . It will send message in game that team 1 forfeited the match first and just a second later sending team 2 forfeited the match message. 
3) Database has same issue START_TIME is set to `NULL` by default and after 10 times the match gets end and send update to database END_TIME that is 10 minutes. For Winner section it will automatically set Team 2 to winner as Team 1 condition of not showing up is calculated first automatically setting Team 2 winner even if it did not join the server. 

Issues here : 
1) As the Start_time is still Null - Match Status is still Pending 
2) Cannot Cancel the match as End_Time is auto updated to 10 Mins as per CVAR and making the match as Completed Match status
3) Winner is set to Team 2 even for not showing up as Team 1 condition of checking time is completed first before team 2 which set automatically team 2 as the winner. 
4) Forfeit is still set to 0 which database has no idea which team forfeited and why .

**Comment by splewis** [comment] 2019-05-25 23:24
There's a lot of details in your bug report that aren't directly relevant to get5 (aka everything involving a database), which means it's probably too time consuming for me to investigate.

I just added some debug logging in 3f793ceb3736d78ba6a92f42631d91cb52f0beb4 that would make it easier to debug. If you can provide a debug log in this situation it might be easier to see the problem.

**Comment by TandelK** [comment] 2019-05-29 10:50
@splewis Debug info on pastebin @ https://pastebin.com/9vxvpnqE

**Comment by tloesch** [comment] 2019-08-18 11:08
@splewis 

i already wrote something to this problem in the get5-web repo. issue.
I found the main problem.

Its the apistats plugin which doesnt send the forfeit information to any endpoint like get5-web.


**Here the comment from the get5-web issue:**

That start_time is still null is the correct behavior in this case.
The match didnt started.

The forfeit features seems not to be implemented completely.
Just look into **models.py** and look at the **status function**s.
There is no check for forfeit.

Then go into **api.py** and look at the **match_finish** function.
There is a forfeit implementation.
But you will not get any forfeit information in this function.

This is caused by the apistats plugin.
Look into the file **get5_apistats.sp** and the function **Get5_OnMapResult**.
The function doesnt send the forfeit information to any endpoint like get5-web.

So there some tasks to do:

implement the forfeit status check in models.py
implement forfeit information transportation into the get5_apistats.sp
Maybe you also need to modify the main get5 plugin to transport the forfeit information to the apistats plugin.

**Comment by PhlexPlexico** [comment] 2022-08-04 16:03
The root cause of said bug is simply because if you have a timeout set in get5 for teams to ready up, the python web-panel doesn't update the start time. This issue has nothing to do with get5, and more to do with the programming that was done on the series result in the web panel itself. 

Get5 sends enough information on a per map basis, that you can infer when the match is completed that it was a forfeit on both sides, one side, etc. That's why this ticket should probably be closed, because all of it could be fixed on the web panel side.

Per the second point in "Tasks to do", you can do this on the web panel side by checking if there are any maps that exist, as well as check the series score to see if the match was forfeit or not. That should be enough data to get by and make a decision if it's been cancelled or forfeit by a team. So, I would say all the work can be done and referenced in https://github.com/splewis/get5-web/issues/152 :) will close this as all work can be done on the web side.

**Closed by PhlexPlexico** 2022-08-04 16:03 UTC
Labels: unverified bug
