### ISSUE TITLE
Backups are restarting game to 0-0

### ISSUE THREAD

**Issue by ndstudios-admin** [splewis/get5#530] opened 2020-05-22 16:14 UTC
Hey!

I have the problem that backup are just restarting match to score 0-0. What do I need to do to fix it?

**Comment by splewis** [comment] 2020-05-22 19:08
>  What do I need to do to fix it?

I don't know. Do you have any more information to share? i.e.


### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):

**Comment by ndstudios-admin** [comment] 2020-05-23 13:42
Debug info:
Plugin version: 0.7.2-dev+480
sourcemod_version = 1.10.0.6488
metamod_version = 1.11.0-dev+1130V
get5 git commit: 1fb5810



Global state:
g_GameState = 0 (none)
g_MatchID = 
g_MapsToWin = 1
g_BO2Match = 0
g_LastVetoTeam = 0
g_MapPoolList (length 0) = 
g_MapsToPlay (length 0) = 
g_MapsLeftInVetoPool (length 0) = 
g_MatchTitle = 
g_PlayersPerTeam = 5
g_MinPlayersToReady = 1
g_MinSpectatorsToReady = 0
g_SkipVeto = 0
g_MatchSideType = 0
g_InScrimMode = 0
g_HasKnifeRoundStarted = 0
g_MapChangePending = 0
g_PendingSideSwap = 0
g_WaitingForRoundBackup = 0
g_SavedValveBackup = 0
g_DoingBackupRestoreNow = 0
g_ReadyTimeWaitingUsed = 0
Team info for team team1 (0):
g_TeamNames = 
g_TeamAuths (length 0) = 
g_TeamTags = 
g_FormattedTeamNames = 
g_TeamFlags = 
g_TeamLogos = 
g_TeamMatchTexts = 
g_TeamSide = CT (3)
g_TeamSeriesScores = 0
g_TeamReadyOverride = 0
g_TeamStartingSide = 3
g_TeamPauseTimeUsed = 0
g_TeamPausesUsed = 0
Team info for team team2 (1):
g_TeamNames = 
g_TeamAuths (length 0) = 
g_TeamTags = 
g_FormattedTeamNames = 
g_TeamFlags = 
g_TeamLogos = 
g_TeamMatchTexts = 
g_TeamSide = T (2)
g_TeamSeriesScores = 0
g_TeamReadyOverride = 0
g_TeamStartingSide = 2
g_TeamPauseTimeUsed = 0
g_TeamPausesUsed = 0
Team info for team spec (2):
g_TeamNames = 
g_TeamAuths (length 0) = 
g_TeamTags = 
g_FormattedTeamNames = 
g_TeamFlags = 
g_TeamLogos = 
g_TeamMatchTexts = 
g_TeamSide = none (0)
g_TeamSeriesScores = 0
g_TeamReadyOverride = 0
g_TeamStartingSide = 0
g_TeamPauseTimeUsed = 0
g_TeamPausesUsed = 0
Team info for team none (3):
g_TeamNames = 
g_TeamAuths (length 0) = 
g_TeamTags = 
g_FormattedTeamNames = 
g_TeamFlags = 
g_TeamLogos = 
g_TeamMatchTexts = 
g_TeamSide = none (0)
g_TeamSeriesScores = 0
g_TeamReadyOverride = 0
g_TeamStartingSide = 0
g_TeamPauseTimeUsed = 0
g_TeamPausesUsed = 0



Interesting cvars:
get5_allow_technical_pause = 1
get5_autoload_config = 
get5_check_auths = 1
get5_fixed_pause_time = 0
get5_kick_when_no_match_loaded = 0
get5_live_cfg = get5/live.cfg
get5_max_pause_time = 300
get5_max_pauses = 0
get5_mysql_force_matchid = 0
get5_pausing_enabled = 1
get5_reset_pauses_each_half = 0
get5_web_api_url = 
mp_freezetime = 15
mp_halftime = 1
mp_halftime_duration = 15.0
mp_halftime_pausetimer = 0
mp_match_end_restart = 0
mp_maxrounds = 30
mp_overtime_enable = 0
mp_overtime_halftime_pausetimer = 0
mp_overtime_maxrounds = 6
mp_round_restart_delay = 7.0
mp_timelimit = 0
mp_warmup_pausetimer = 0
mp_warmuptime_all_players_connected = 60
sv_coaching_enabled = 0
tv_delay = 105
tv_enable = 1



Last log info from addons/sourcemod/logs/errors_20200523.log:
L 05/23/2020 - 13:32:41: [SM] Unable to load plugin "lsd_nozoom.smx": Could not find required plugin "lsd"

---
What did I do? I just played3 rounds and typed !stop. Then it said that backup config successfully loaded and the match will restart in 5 sec. And so score went 0-0.

**Comment by PhlexPlexico** [comment] 2022-07-03 16:14
I believe https://github.com/splewis/get5/pull/652 has resolved this issue, and since it's been about two years since a response, I'm going to close it. If there's anymore issues, feel free to join the [Discord](https://discord.gg/zmqEa4keCk) :)

**Closed by PhlexPlexico** 2022-07-03 16:14 UTC
Labels: user help

**Comment by DarkTwistter** [comment] 2022-12-16 19:14
The same issue with release v0.11.0

```get5_backup0_matchpizzadebils_map0_round3.cfg```

**Comment by PhlexPlexico** [comment] 2022-12-16 19:17
Would you mind attaching the backup file?

**Comment by DarkTwistter** [comment] 2022-12-16 19:19
> Would you mind attaching the backup file?

Sure, here it is
https://gist.github.com/DarkTwistter/13b466b985005a57dc2d4c0de8a59aed

**Comment by PhlexPlexico** [comment] 2022-12-16 19:31
The gist you uploaded was round 3, which the score states that it is 1-1. Your filename even states this - `get5_backup0_matchpizzadebils_map0_round3.cfg`.
