### ISSUE TITLE
[Request Feature] !techpause

### ISSUE THREAD

**Issue by MikkelDK** [splewis/get5#240] opened 2018-03-29 22:32 UTC
Hi,

Is there some way, where i can make my own !command via get5 to be used?

i'm not 100% sure, where i need to "look" as example (if i need to find where !pause) is saving, for adding !techpause

As example like this:
mp_team_timeout_time 30
mp_team_timeout_max 4
timeout_ct_start (CT)

**Comment by Technoblazed** [comment] 2018-03-29 22:33
Duplicate of https://github.com/splewis/get5/issues/62

**Closed** 2018-03-29 22:36 UTC
