### ISSUE TITLE
Always BO1 

### ISSUE THREAD

**Issue by AFreeman94** [splewis/get5#180] opened 2017-08-24 03:17 UTC
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior

When changing the num_maps to 3 it would expect that the veto would then make its way until 3 maps are available however instead its veto's all the way down to one map and only allows one map to be played before ending the series

### Actual behavior

Regardless of the num_map option in my json array the veto always goes down to one map and only plays that map.

### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these.

- Plugin version: 0.5.3-dev+334
- Sourcemod version: 1.8.0.6017

get5_status printout
` ] get5_status
{
    "map_number": 0,
    "plugin_version": "0.5.3-dev+334",
    "gamestate": 3,
    "gamestate_string": "warmup",
    "commit": "1424c1c",
    "paused": false,
    "matchid": "4",
    "loaded_config_file": "remote_config101.json",
    "team1": {
        "current_map_score": 0,
        "connected_clients": 1,
        "side": "CT",
        "name": "EnvyUs",
        "series_score": 0,
        "ready": false
    },
    "team2": {
        "current_map_score": 0,
        "connected_clients": 1,
        "side": "T",
        "name": "Fnatic",
        "series_score": 0,
        "ready": false
    },
    "maps": {
        "map0": "de_train"
    }
}`

JSON file loaded onto server (it is the example_match.json)
```
{
	"matchid": "example_match",
	"num_maps": 3,
	"players_per_team": 1,
	"min_players_to_ready": 1,
	"min_spectators_to_ready": 0,
	"skip_veto": false,
	"veto_first": "team1",
	"side_type": "standard",

	"spectators": {
		"players":
		[
			"STEAM_1:1:.....",
			"STEAM_1:1:.....",
			"STEAM_1:1:....."
		]
	},

	"maplist":
	[
		"de_cache",
		"de_cbble",
		"de_inferno",
		"de_mirage",
		"de_nuke",
		"de_overpass",
		"de_train"
	],

	"favored_percentage_team1": 65,
	"favored_percentage_text": "HLTV Bets",

	"team1": {
		"name": "EnvyUs",
		"tag": "EnvyUs",
		"flag": "FR",
		"logo": "nv",
		"players":
		[
			"STEAM_0:1:52245092",
			"STEAM_1:1:.....",
			"STEAM_1:1:.....",
			"STEAM_1:1:.....",
			"STEAM_1:1:....."
		]
	},

	"team2": {
		"name": "Fnatic",
		"tag": "Fnatic",
		"flag": "SE",
		"logo": "fntc",
		"players":
		[
			"STEAM_1:1:46796472",
			"STEAM_1:0:78189799",
			"STEAM_1:0:142982",
			"STEAM_1:1:.....",
			"STEAM_1:1:....."
		]
	},

	"cvars": {
		"hostname": "Match server #1"
	}
}
```

**Comment by splewis** [comment] 2017-08-24 03:27
How are you testing this? You're definitely not any of the steamids in that file, so you must be doing other steps.

**Comment by AFreeman94** [comment] 2017-08-24 03:41
I have check auths at 0

**Comment by AFreeman94** [comment] 2017-08-24 04:14
Update: even when using check_auth 1 and entering the correct steam ids the
error still exists with the num_map feature. Regardless of the number of
maps entered the veto always limits the match to one map.

The servers are running off Debian

**Comment by splewis** [comment] 2017-08-24 05:03
Can you try doing a test without vetoing enabled? It's hard for me to test the veto system since it requires 2 players. I can do tests alone if I don't need to veto.

If there's no issue with that, then it's a veto system bug (which seems very plausible).

**Comment by AFreeman94** [comment] 2017-08-24 13:06
I ran the test with skip veto true, it loaded the maps in order from the
map list until a winner was determined based on endseries function. It
appears this is running functionally.

I then used myself and one other player with check auth 1 and skip veto
false. It appears the issue may be within the veto system itself as with
these conditions the veto then only allowed one map to remain after veto
and then played only that one map.

Let me know if you need me to do anything else for debugging

**Comment by splewis** [comment] 2017-08-25 03:06
Thanks, I've reproduced the issue. Looking to see what's going on...

**Comment by AFreeman94** [comment] 2017-08-25 03:10
Awesome thank you so much, I was trying to trouble shoot all day today. I
was suspicious it may be the bo3_hook function as the ban/ban/pick/pick/ban
is different than your older versions in which the players veto until the
specific number of maps remain.

If you need me to do anything to help resolve the issue let me know

**Comment by splewis** [comment] 2017-08-25 03:19
https://github.com/splewis/get5/commit/c60492251ee1fbc169eca853c9ef5dd8c89c32a6 should have fixed it. 

Can you try build 336? https://ci.splewis.net/job/get5/336/

I've also added a get5_debuginfo command which I think will help a lot in situations like these.

**Comment by AFreeman94** [comment] 2017-08-25 20:13
Hey splewis I can confirm after 5 tests that the issue still arises, not once did the veto behave as expected with these changes.

**Comment by splewis** [comment] 2017-08-26 03:09
I'm having trouble understanding your response. 

> maps_to_win function 

It's a data file. There's no functions. ``maps_to_win`` is a deprecated field now (replaced by num_maps), and I don't suggest using it. I **definitely** don't suggest using both fields. ``maps_to_win`` and ``bo2_series`` will likely be removed at some point.

> not using an automated php setup system

I also don't know what you mean. I'm not sure how php is relevant, but this is entirely an issue with get5 reading match configs. How the configs are created or how they get on the server doesn't matter.

**Comment by AFreeman94** [comment] 2017-08-26 03:50
The only way I could get the veto system to function properly was by using `
"num_maps": 3,
"maps_to_win": 2,
`

as for the php system i was referring to others who dont use the get5-web but instead use php to print JSON arrays from their own databases to build the desired information into the match config (.json).

**Comment by splewis** [comment] 2017-09-10 21:18
As far as I can tell in my testing ``maps_to_win`` works as expected, so I'm closing this.

**Closed by splewis** 2017-09-10 21:18 UTC
Labels: bug

**Comment by AFreeman94** [comment] 2017-09-10 21:29
You said not to use maps_to_win because you plan on removing it no?

**Comment by splewis** [comment] 2017-09-10 21:37
Sorry, I meant ``num_maps`` working as expected.
