### ISSUE TITLE
Can't init and killing the server

### ISSUE THREAD

**Issue by burhan-kun** [splewis/get5#320] opened 2018-11-20 01:20 UTC
Hello,

I have a problem with my installation of Get5 and the servers. The problem does not always occur, it occurs very sporadically. Do you have any idea why this might be? (translator)

Nov 20 01:10:12:  sv_waterfriction - 1
Nov 20 01:10:12:  tv_delay - 10
Nov 20 01:10:12:  weapon_accuracy_nospread - 0
Nov 20 01:10:12:  weapon_air_spread_scale - 1.0
Nov 20 01:10:12:  weapon_max_before_cleanup - 0
Nov 20 01:10:12:  weapon_recoil_scale - 2.0
Nov 20 01:10:12:  weapon_reticle_knife_show - 0
Nov 20 01:10:12:  ff_damage_reduction_grenade - 0.25
Nov 20 01:10:12:  ff_damage_reduction_grenade_self - 1
Nov 20 01:10:12:  ff_damage_reduction_other - 0.25
Nov 20 01:10:12:  mp_friendlyfire - 0
Nov 20 01:10:12:  mp_warmuptime - 30
Nov 20 01:10:12:  mp_warmuptime_all_players_connected - 0
Nov 20 01:10:12:  Executing dedicated server config file
Nov 20 01:10:12:  L 11/20/2018 - 01:10:12: server_cvar: "nextlevel" ""
Nov 20 01:10:12:  L 11/20/2018 - 01:10:12: server_cvar: "mp_autoteambalance" "0"
Nov 20 01:10:12:  L 11/20/2018 - 01:10:12: server_cvar: "mp_limitteams" "0"
Nov 20 01:10:12:  L 11/20/2018 - 01:10:12: server_cvar: "mp_timelimit" "0"
Nov 20 01:10:12:  L 11/20/2018 - 01:10:12: server_cvar: "sv_deadtalk" "1"
Nov 20 01:10:12:  Can't use cheat cvar sv_grenade_trajectory in multiplayer, unless the server has sv_cheats set to 1.
Nov 20 01:10:12:  Console: "Warmup loaded"
Nov 20 01:10:12:  L 11/20/2018 - 01:10:12: "Console<0><Console><Console>" say ""Warmup loaded""
Nov 20 01:10:12:  L 11/20/2018 - 01:10:12: get5_event: {
Nov 20 01:10:12:      "params": {
Nov 20 01:10:12:          "map_name": "de_overpass",
Nov 20 01:10:12:          "map_number": 0,
Nov 20 01:10:12:          "message": "\"Warmup loaded\"",
Nov 20 01:10:12:          "client": "none"
Nov 20 01:10:12:      },
Nov 20 01:10:12:      "matchid": "131",
Nov 20 01:10:12:      "event": "client_say"
Nov 20 01:10:12:  }
Nov 20 01:10:12:  L 11/20/2018 - 01:10:12: Starting Freeze period
Nov 20 01:10:12:  Can't init trigger_soundoperator
Nov 20 01:10:12:  Can't init logic_relay
....
...
Nov 20 01:10:12:  L 11/20/2018 - 01:10:12: World triggered "Match_Start" on "de_overpass"
Nov 20 01:10:13:  Segmentation fault
Nov 20 01:10:13:  --- SERVER EXITED ---

**Comment by burhan-kun** [comment] 2018-11-20 07:13
Hello,

the problem is after load the Match Config. If a User try to join the Server, they load more configs like warmup.cfg (The first Player) and maybe then the server going down. If no player joins, that not going down. From 10 Times / 1 Time it going down. Can i force the process like exec warmup.cfg with my rcon? Works this? Or is this not the same thing..?

**Comment by burhan-kun** [comment] 2018-11-20 16:59
Maybe, the server is going offline only if i load get5_match_config - but 1 times it works, 1 times not. I installed the accellerator for better debug'in.

I load over a json in my server the match config, after this the server works always fine. The problem is, if the first player trying to joing the server, then the script loads more like "get5_time_to_start" - and after load this scripts (i dont kno what) i become the error sporadically.

Can i force the process from the loading instantly by load the match config and not by joinging the server?

Actual: I load match config, timer "get5_time_to_start" countdown is not active - The countdown is only active when the first player tries to join. But I want the countdown to be active right away when it loads a config, so no idea what he's doing before, I want to get the process / function started right away.

**Comment by burhan-kun** [comment] 2018-11-20 18:36
Ok, now the process forces. I add:
sv_hibernate_when_empty 0

But the error i the same - but now i check after load a config the server.. :-)

**Comment by TandelK** [comment] 2018-11-21 12:09
Can you check the GLST Server Token access ?  Also add -condebug to start up list and it will auto create console.log file in CSGO folder. paste that file on pastebin and share it here.

**Comment by splewis** [comment] 2018-11-22 03:32
Unfortunately the probability of fixing any non-reproducible crash is extremely low. Without a useful crash dump from [accelerator](https://forums.alliedmods.net/showthread.php?t=277703&), it's effectively 0.

**Comment by splewis** [comment] 2018-11-30 05:57
Closing since there's been no update. No accelerator crashdump means there's nothing anyone can do to help.

**Closed by splewis** 2018-11-30 05:57 UTC
