### ISSUE TITLE
moveplayer (team) failed console spam crashes server

### ISSUE THREAD

**Issue by kubo6472** [splewis/get5#734] opened 2022-01-07 14:30 UTC
### Expected behavior

The server doesn't crash when players keep trying to switch a team.

### Actual behavior

It spams console with moveplayer (team) failed and if excercised long enough, crashes the server

### Steps to reproduce

Have player trying to switch team for circa 5 minutes.
The console gets spammed.
The server crashes.
Possibly related to #732 

get5_debuginfo: https://www.toptal.com/developers/hastebin/vunupideko.makefile

**Comment by nickdnk** [comment] 2022-01-08 04:44
@kubo6472 When you say "for circa 5 minutes" do you mean someone clicking the opposite team for five minutes straight without anything happening?

**Comment by kubo6472** [comment] 2022-01-08 10:59
> do you mean someone clicking the opposite team for five minutes straight without anything happening?

If you specify players, they're locked to a team, right. If someone's for 5 minutes trying to switch the team, which is impossible, the server crashes.

**Comment by nickdnk** [comment] 2022-01-14 23:19
@kubo6472 Can you perhaps join the Discord? We need more people to test stuff and also it's just easier to communicate in direct chat: https://github.com/kubo6472

**Comment by PhlexPlexico** [comment] 2022-06-22 21:12
Okay, looks like we had another user in Discord find a way to reproduce this. Attached is the file that they are using trying to load it, and they are running into the same issue. They're playing wingman game mode (game type 0, game mode 2), and using maps that contain warmup areas that CS has introduced. So Vertigo causes this issue, but something like shortdust doesn't.

The docker image being used with sourcemod is cm2network/csgo:sourcemod.

Maybe this can lead to a reproducible crash now and we can get some more eyes on it?

[crashing_config.txt](https://github.com/splewis/get5/files/8961308/crashing_config.txt)

**Comment by PhlexPlexico** [comment] 2022-06-23 17:22
Okay, some more messages in Discord, and I think the reason why it's failing is a known CS:GO game bug, per their [documentation](https://developer.valvesoftware.com/wiki/Setting_up_1v1_Warmup_Arenas).

**Warning**: Having more than 5 players on one team causes an infinite loop freezing the game!

I think this may be the same for if you're playing on Wingman with more than 2 on a team, as only 2 arenas are used, so if there are 3 people on a team in wingman, it's going to cause this crash.

@kubo6472 by any chance do you have people joining the teams, waiting for everyone to join on a map that has a warmup arena, and if a person doesn't go into the coach slot, does the game crash? Or if it's a Wingman and you're playing with more than two players per team, does this cause it to crash?

Thanks!

**Comment by kubo6472** [comment] 2022-06-23 18:23
I'm pretty sure this was happening only with coach(es) present.

**Comment by tapir** [comment] 2022-06-28 22:43
I can confirm that more than 4 people will crash wingman gamemod.
The only viable workaround that I could find was to disable sv_pure and change the scripts/vscripts/warmup/warmup_teleport.nut script to have WINGMAN = false in OnPostSpawn(). It's an ugly hack and it won't work for competitive.

**Comment by nickdnk** [comment] 2022-06-30 21:41
I don't think this is a get5 problem at all. Can we close this?

**Comment by tapir** [comment] 2022-06-30 21:43
it's not but somehow get5 always triggers arena warmup mode. I can't disable it completely.

**Comment by PhlexPlexico** [comment] 2022-06-30 21:47
That's because CS does this by default when setting the game mode to competitive, per the gameplay description - https://developer.valvesoftware.com/wiki/Setting_up_1v1_Warmup_Arenas#Gameplay_Description

Not much we can do to fix this unfortunately unless you use the disable warmup plugin I think?

**Comment by nickdnk** [comment] 2022-06-30 21:47
But with get5 you should not have more than 4 in wingman and 10 in a regular game. If you have, you are outside the bounds of what get5 is meant to do.

**Comment by kubo6472** [comment] 2022-07-01 13:15
I have warmup arenas turned off, it should not impact this behavior. Basically: The users are in some teams, one team is CT, one is T, if the users keep trying to switch a team, with get5 not letting them to, it will crash the server. We had some coaches in every game. So even though the "only with coaches" may've been a bit of a stretch to say right away, I doubt any kind of deeper cause was behind this.

**Comment by tapir** [comment] 2022-07-01 13:25
> That's because CS does this by default when setting the game mode to competitive, per the gameplay description - https://developer.valvesoftware.com/wiki/Setting_up_1v1_Warmup_Arenas#Gameplay_Description
> 
> Not much we can do to fix this unfortunately unless you use the disable warmup plugin I think?

fair enough. could you share a link to that plugin? would be useful for future reference too

**Comment by kubo6472** [comment] 2022-07-01 13:29
https://github.com/Ilusion9/csgo-fix-warmup-sm/blob/main/scripting/fix_warmup.sp

**Comment by tapir** [comment] 2022-07-01 13:32
interestingly the script does nothing specific to "competitive" mode. it would work on wingman too. I like it as a workaround.

**Comment by nickdnk** [comment] 2022-07-15 01:44
Closing this as it doesn't seem to be a get5 issue. @tapir If you want to make a fix for a warmup disable, open a new one.

**Closed by nickdnk** 2022-07-15 01:44 UTC
Labels: unverified bug

**Comment by kubo6472** [comment] 2022-10-11 09:23
https://github.com/Ilusion9/csgo-fix-warmup-sm/blob/main/scripting/fix_warmup.sp
