### ISSUE TITLE
Hostname not being restored after match finish

### ISSUE THREAD

**Issue by mrc4tt** [splewis/get5#438] opened 2019-10-22 06:14 UTC
Hi,

It could be nice to get little function on get5 plugin, with a little change after the match is finished, so "hostname" aka servername will be changed back as normal from "server.cfg"

Example:
Match1 > Hostname: Get5: Mikkel vs Test1 
After 16-0 - where the match is finished.
Server is still having "Get5: Mikkel vs Test1" as servername.
The server should have changed the server name to what it has from server.cfg:
Example: 
1) Get5: Mikkel vs Test1 (Match)
2) Mikkel's Server (After Match is finished) - exec from the server.cfg (from get5 plugin)

**Comment by splewis** [comment] 2019-10-23 01:51
Are you sure that's not *already* happening? get5 has some code already that saves previous cvar values before execution & restores them later, but things get a bit confusing since there's both the warmup & live config. 

Can you make sure to check the actual ``hostname`` cvar in console? The display on the scoreboard isn't an accurate reflection of the cvar, the last time I checked (it only seemed to update on map loads).

**Comment by MikkelDK** [comment] 2019-10-23 15:29
It doesn't change the hostname of Get5: Mikkel vs Test1 to Mikkel's Server (from server.cfg) after the match is finished. which it doesn't do.

Aka:
```
  g_SetHostnameCvar = CreateConVar(
      "get5_hostname_format", "Get5: {TEAM1} vs {TEAM2}",
```
**After MATCH is done with 16-0** - **It's still running with Get5: Test1 vs Test2** - My question is: Isn't it supposed to change the server name back as it was called when the game is over, or what?

**Example:**
**Game1: Hostname will be: Get5: spelwis vs mikkel**
**Game1 is finish 16-0 to spelwis** - Here is the problem, **It don't exec server.cfg OR change hostname back as it was before match was started!**

**Comment by splewis** [comment] 2019-10-26 03:18
> After MATCH is done with 16-0 - It's still running with Get5: Test1 vs Test2

I understand that. I'm asking how you're determining what "it" is. Are you:
1) Looking at the scoreboard in-game
2) Checking the value of the cvar via console (like `sm_cvar hostname` or such)

If you think there is indeed a bug, you should post steps to reproduce as well.

**Comment by MikkelDK** [comment] 2019-10-26 05:45
Checking the value of the cvar via console (like sm_cvar hostname or such) & checking the server on favorites (via Steam)

**Comment by DennisF10** [comment] 2020-03-31 02:00
I can confirm that hostname doesn't change back, no matter if you check server browser, scoreboard or sm_cvar hostname etc.

**Comment by ndstudios-admin** [comment] 2020-06-23 14:27
Yes, I can agree. I have the same issue with backups.

**Comment by Drarig29** [comment] 2021-03-14 12:24
@MikkelDK is that fixed? Why did you close it?

**Comment by MikkelDK** [comment] 2021-03-14 12:52
@Drarig29 No.

I did close it because it will not be made/fix (since I have waited). And I'm not an SM coder, so I can't make PR.
It didn't change "hostname" back to the default hostname (after the game is finish).

**Comment by Drarig29** [comment] 2021-03-14 13:02
Okay, then it's a real bug. I think this should be reopened and marked with the 'bug' label. Maybe it needed a little bump.

It's just quite hard to debug it, maybe it's a timing issue. Just need someone to investigate.

@splewis what do you think?

**Closed** 2022-11-17 02:06 UTC
Labels: bug
