### ISSUE TITLE
Crash on map changing at BO3 matches

### ISSUE THREAD

**Issue by khtsn** [splewis/get5#224] opened 2018-01-22 16:54 UTC
First time posting an issue 🗡 

### Expected behavior
Map changed successfully

### Actual behavior
Game server crashed and lost the match status

### Steps to reproduce
(Server info: Cloud VPS, 2 core Xeon and 4 GB RAM, Debian and Ubuntu)
1. Load a 5v5 BO3 match via get5_loadmatch_url
2. Play until the end of a map and then wait for changing map (wait for GOTV broadcast ended)
3. Game server crashed

### More info
1. If admin change the map first before the game server triggering change map, it will work as normal, but get another map changing when playing (just like sm_map x2)
2. 1v1 is okay on testing, but on 5v5 is crashed. I tried on 8GB RAM but still same result. Will try on Windows later.

- Plugin version: 0.5.2
- Sourcemod version: 1.8.0.6038

**Comment by splewis** [comment] 2018-01-23 03:05
Those steps to reproduce aren't really steps to reproduce - I need actionable steps to reproduce the problem (I've done that sequence of things before without any problems).

Diagnosing any crash pretty much requires installing [Accelerator](https://forums.alliedmods.net/showthread.php?t=277703), and then getting a crash dump url. Can you try that?

**Comment by khtsn** [comment] 2018-01-23 03:06
Sure, I will try it.

**Comment by khtsn** [comment] 2018-02-01 19:25
@splewis 
I tried using Accelerator, but it still crashed with empty dumps.

Here are the steps to reproduce, I think that would be easy but take time 🗡 . I just need 2 players to make it crashed.
1. Load a match 5v5, Bo3 mode, add 8 more bots for a 5v5 match
2. Try to play to the end of a map, 16 - 0 and then wait for map changing
3. Server crashed.

Note:
I tried enable -debug when server crashed, and it show this errors:
steamnetworkingsockets_lowlevel.cpp (92) : Assertion Failed: SteamDatagramTransportLock held for 30.4ms! 
steamnetworkingsockets_lowlevel.cpp (92) : Assertion Failed: SteamDatagramTransportLock held for 60.4ms! 

I think it would be hard for you, but no error is dumped after crashing :(

**Comment by Technoblazed** [comment] 2018-02-01 19:46
Accelerator wouldn't create empty dumps if it was installed correctly, are you positive no dumps are being created?

**Comment by khtsn** [comment] 2018-02-03 13:50
@Technoblazed 
Yes, no dumps, checked accelerator.log and its empty too.

GOTV enabled with 120s delay, 128 tick snapshot.

**Comment by Technoblazed** [comment] 2018-02-03 17:40
Your issue is with gotv, not positive what the cvar is, but make sure the get5 cvar for the time before the match is changed, in order to account for the gotv delay is set.

**Comment by khtsn** [comment] 2018-02-03 18:04
@Technoblazed 
Could you explain more detail? Or an example, I'm too confused :(

BTW, I tried 105s and 120s and game server still got crashed.

**Comment by Technoblazed** [comment] 2018-02-03 18:33
Could you set tv_delay to 0 in your gamemode_competitive_server.cfg and tell me if it still crashes?

**Comment by khtsn** [comment] 2018-02-03 20:12
It works! I wonder why?

Also tried on 10s, 30s, 60s, it works too!
But crashed on 90s.

**Comment by Technoblazed** [comment] 2018-02-03 20:17
Okay so, this is really difficult to explain.

I first noticed this issue with pug-setup but it applies to cs in general. I'll try and provide an explanation:

When the match finishes, the GOTV bot is still playing through the match. If the delay of the GOTV is longer than the time before the map is changed from the initial match, the server will crash. I can only imagine that this is due to the GOTV client still recognising that there is still a demo being recorded due to the delay, obviously it's a game bug, but yeah.

**Comment by khtsn** [comment] 2018-02-03 20:23
I got your point :)

I still have a question, why it crashes on about 10+ slots only? I tried with 1v1 (2 slots) and it always works normally. That's the reason that I don't think the issue is on the GOTV.

Thank you very much for supporting me on this issue :D

**Comment by Technoblazed** [comment] 2018-02-03 20:24
Not too sure, but I'd like to fix the GOTV issue regardless, if you could get the output of `mp_match_restart_delay` that'd be great.

**Comment by khtsn** [comment] 2018-02-03 20:33
Tried on some cases

tv_delay 105 ==> mp_match_restart_delay = 120
tv_delay 60 ==> mp_match_restart_delay = 75

**Comment by Technoblazed** [comment] 2018-02-03 20:34
Well that part works right. Honestly have no idea, maybe splewis has a better insight onto it :^)

**Comment by khtsn** [comment] 2018-02-03 20:38
One more thing that I discovered is all RAM is used when changing the map. With a 5v5 match, the RAM usage is around 1.5 ~ 2 Gbs, then pushed to max 3.99 Gbs on map change.

Also tried on a VPS with 8 Gbs, it pushed to 7.99 Gbs on map change.

**Comment by Technoblazed** [comment] 2018-02-03 20:52
That definitely doesn't seem like something your server should be doing, I've never had that on servers in the past.

**Comment by TandelK** [comment] 2018-02-05 14:14
The RAM bug has been there from Sourcemod also . If you use !rtv and use !map by admin than the server will become timeout for few seconds and than respond again

**Comment by splewis** [comment] 2018-02-18 22:58
Without a crash dump there's nothing I can really do to help - there's also no sign this is related to get5 itself yet.

**Comment by splewis** [comment] 2018-03-11 05:39
I'm closing since I have no reason to believe get5 is directly related to this.

**Closed by splewis** 2018-03-11 05:39 UTC

**Comment by khtsn** [comment] 2020-03-23 18:08
Hi, sorry for bump this again.
Luckily I have the dump file from Accelerator.
[crash_4dlka6gdhrlz.zip](https://github.com/splewis/get5/files/4371137/crash_4dlka6gdhrlz.zip)

Cheers,
