### ISSUE TITLE
Loop when all players are ready (not fixed)

### ISSUE THREAD

**Issue by EAbychkov** [splewis/get5#184] opened 2017-09-10 17:16 UTC
### Expected behavior
Match starts when all the 10 players are ready

### Actual behavior
Loop in chat = "The match will begin in 60 seconds"

### Steps to reproduce
Only reproduce when all 10 players take place

- Plugin version: 0.5.3-dev+334
- Sourcemod version: 1.8.0.6014

**Comment by splewis** [comment] 2017-09-10 18:11
Can you provide a match config? Or get a [debug dump](https://github.com/splewis/get5/wiki/Debugging-help#getting-a-debug-dump) when it happens?

**Comment by EAbychkov** [comment] 2017-09-10 19:23
get5_debuginfo says "unknown command"
get5_version works correctly. 
Unfortunately nothing useful in logs file (((

**Comment by splewis** [comment] 2017-09-10 19:29
Sorry, the debug command was added recently, so you need a newer build to use it.

As for debug logs: you have to set the get5_debug cvar for any logging to happen. Just setting it then looking for the log file isn't enough, you have to set it earlier.

**Comment by EAbychkov** [comment] 2017-09-10 20:33
Unfortunately, it's hard for me to find 10 players to test it again in recent time. 
Can we Just get rid of this message somehow? 
Everything works just perfect if there are 3 vs 3 or 4 vs 4, 
but if there are 5 vs 5 this message start looping (((

**Comment by EAbychkov** [comment] 2017-09-10 20:35
Please check this out, it's not in English, but the message the same. 

![jdy_o14tyk4](https://user-images.githubusercontent.com/1067550/30252753-b69a16d4-9680-11e7-9a8b-1506965724a1.jpg)

**Comment by splewis** [comment] 2017-09-10 20:46
The message isn't the problem. Not starting the match is the problem.

**Comment by EAbychkov** [comment] 2017-09-10 20:52
But this message shows in an infinitely loop.

**Comment by splewis** [comment] 2017-09-10 21:16
If the match doesn't start, deleting the chat message won't make it start. 

My point was that your suggestion of 

> Can we Just get rid of this message somehow?

is not going to help.

**Comment by EAbychkov** [comment] 2017-09-11 13:24
What is the normal behaviour in this case? 
Do this message really should loop for 60 seconds ruining all the player's messages?

**Comment by splewis** [comment] 2017-09-12 00:51
The normal behavior is that it prints once and the match starts.

**Comment by EAbychkov** [comment] 2017-09-12 09:57
What can I do to help you to fix it? 
I really need it to be fixed.

**Comment by EAbychkov** [comment] 2017-09-12 10:25
I just found this potential solution:
> mp_warmuptime_all_players_connected 0
Not sure if it will work, but it might help someone suffering from the same problem.
I'll check it as soon as I get 10 players and write down over here the result of my test.

**Comment by splewis** [comment] 2017-09-13 00:51
Like I originally said, getting debug logs or a debug dump from a newer version is how you could help.

Or reproducible steps (ideally with 2 players).

It's also still not clear to me if the match is starting for you or not. Is it?

**Comment by splewis** [comment] 2017-10-21 00:28
I'm closing this because I never got reproducible steps or a clear explanation of what the bug was.

**Closed by splewis** 2017-10-21 00:28 UTC
