### ISSUE TITLE
skip_veto doesn't work as expected

### ISSUE THREAD

**Issue by EAbychkov** [splewis/get5#311] opened 2018-10-16 08:11 UTC
### Expected behavior
In case of **skip_veto = 1** there is no messages like: 

> Type !ready when your team is ready to veto.  

And no need to reload the map after !ready command typed if the currently loaded map is already correct. 

### Actual behavior
1) Message => Type !ready when your team is ready to veto.
2) Map reloaded

### Steps to reproduce

set skip_veto = 1

- Plugin version: 0.6.0
- Sourcemod version: 1.9 - build 6260

**Comment by splewis** [comment] 2018-10-16 17:05
skip_veto works for me, so I'm going to need your match config, as well as what nap you're on when you run it (as reported by running the status command in console).

**Comment by splewis** [comment] 2018-10-23 03:03
Without any steps to reproduce this, I'm going to close it.

Feel free to reopen if you can provide the information about the map + match config you're using.

**Closed by splewis** 2018-10-23 03:03 UTC
Labels: user help

**Comment by mgjuhler** [comment] 2019-05-02 11:42
[get5.smx] Type mismatch for key "skip_veto", got string when expected a bool

skip_veto needs to be true or false, not 0 or 1
