### ISSUE TITLE
Invalid Match JSON

### ISSUE THREAD

**Issue by PhlexPlexico** [splewis/get5#364] opened 2019-04-10 00:41 UTC
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior
Get 5 successfully loads match

### Actual behavior
json_decode: expected key string at 75 when trying to load match from URL.

### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version: 0.7.1+458
- Sourcemod version: 1.9
- Steps to reproduce (please be specific):
Use the get5-webpanel to load the match config, receive error in console on server.

Just reporting this from issue https://github.com/splewis/get5-web/issues/147. Seems there's an issue parsing out the JSON with a "+Build#" version?

I know the previous one was reported, but here's a proper bug report and apparently how to reproduce.

**Comment by splewis** [comment] 2019-04-10 03:33
Thanks.

I confirmed the 0.7.1 release works fine.

I'm guessing the latest dev build has some of the changes I see in the sm-json repository since then: https://github.com/clugg/sm-json/commits/master

I haven't confirmed that's the source of the issue, though.

**Comment by thboss** [comment] 2019-04-20 22:42
I recompiled plugin for latest json version
get this error
L 04/21/2019 - 00:21:50: [get5.smx] json_decode: couldn't extract string at 631
L 04/21/2019 - 00:21:50: [get5.smx] Failed to load match config: invalid match json
plugin version 0.7.1
SM 1.10

**Comment by splewis** [comment] 2020-04-12 01:19
I think this has been fixed now? Feel free to reopen if not.

**Closed by splewis** 2020-04-12 01:19 UTC
Labels: bug

**Comment by s1inche** [comment] 2022-04-23 18:55
Have you found a solution to this problem?

**Comment by PhlexPlexico** [comment] 2022-04-23 19:36
You have to make sure you have the SteamWorks extension enabled if you're loading the match remotely. If you don't have all the requirements for the plugin, it will most likely fail.

**Comment by s1inche** [comment] 2022-04-23 19:42
All plugins work
get5_apistats.smx / G5WS.smx
get5.smx
But when creating a match, it gives this error.

Maybe show you some configs? I just don't understand what to do

**Comment by PhlexPlexico** [comment] 2022-04-23 20:05
Do you have the SteamWorks extension installed though? `sm exts list`

**Comment by s1inche** [comment] 2022-04-26 20:15
![image](https://user-images.githubusercontent.com/54583646/165384520-5e5ae15e-7b8d-4af4-8657-b44e634264e0.png)
It seems to be, but I don't see SteamWorks here, is that true?

**Comment by PhlexPlexico** [comment] 2022-04-26 20:21
`SteamWorks` is not in your install. I believe the latest release is [here](https://github.com/hexa-core-eu/SteamWorks/releases) and it needs to be placed in `addons/sourcemod/extensions`, make sure you include either the .dll or .so depending on what environment your game server is running on.

**Comment by s1inche** [comment] 2022-04-26 20:25
![image](https://user-images.githubusercontent.com/54583646/165385812-c150976e-1874-46c4-81b7-5df2464c1978.png)
![image](https://user-images.githubusercontent.com/54583646/165385865-775eb54b-0aa6-43bb-98d7-3c7de556ae53.png)
It's already in the sourcemod 6517 Windows folder.
SteamWorks 131 Windows
What could be wrong? Or try reinstalling sourcemod and metamod

**Comment by s1inche** [comment] 2022-04-26 20:33
Yes, I completely reinstalled sourcemod and metamod. And everything worked. Thank you!
![image](https://user-images.githubusercontent.com/54583646/165387497-10b3edfd-921e-4035-8969-b2a4ae5b1d26.png)

**Comment by s1inche** [comment] 2022-04-26 20:38
![image](https://user-images.githubusercontent.com/54583646/165388242-75ad219a-58e3-40d4-9ca6-f16ef245184d.png)
But this did not fix the error that was thrown when creating a match. What could be the problem?)

**Comment by PhlexPlexico** [comment] 2022-04-26 20:39
It's exactly what the error message states. What is the match config that you are trying to load?

**Comment by s1inche** [comment] 2022-04-26 20:45
I am using 5x5 game through G5V.  My commands are removed from challongeone.com |  Could it be anxiety?  Also, I did not find the Steam IDs of other players.  Only the title.

**Comment by PhlexPlexico** [comment] 2022-04-26 20:53
I'm not exactly sure what you're saying... you're using an API to create matches, and using Challonge to import teams and seasons?

If so, you still need to define the team members. Just because it brings in the teams, you still need to put in the steam IDs as well. Do you have a link for the match config? If you're using G5API you can view it with `http://yourserver.com/api/matches/<match_number>/config`. That being said, if you're having trouble with this, it's not really the place to discuss that either, I would go ahead and create a new [discussion](https://github.com/PhlexPlexico/G5V/discussions/new) in the proper project :)

Thanks!

**Comment by s1inche** [comment] 2022-04-26 20:55
Thanks for the explanation, you are the best!  I'm sorry I can't help you financially, our cards are blocked for payment in other parts of the world(

Thanks!

**Comment by s1inche** [comment] 2022-04-26 21:01
What does it mean?  When you go to the match config on the site.![image](https://user-images.githubusercontent.com/54583646/165391684-0e6580e8-f641-4c8f-9721-65b874858d4d.jpeg)

**Comment by PhlexPlexico** [comment] 2022-04-26 21:10
This is not the place for that discussion, if you wish feel free to reply here - https://github.com/PhlexPlexico/G5API/discussions/193

Thanks!
