### ISSUE TITLE
get5_kick_immunity "1" not working with sm admin flags

### ISSUE THREAD

**Issue by TheUdK** [splewis/get5#372] opened 2019-04-16 20:58 UTC
### Expected behavior

Allow admin to join on server with no match loaded.

### Actual behavior

Disconnect: There is no match setup.

### Steps to reproduce

- Plugin version: "get5_version" = "0.7.1" 
- Sourcemod version: 1.9.0.6276
- Steps to reproduce (please be specific):

1. Add admin to admins_simple.ini with either "STEAMID" "99:abcdefghijklmn" or "99:g" or "g" or "99:z"
2. Set get5.cfg cvars to:
-get5_kick_immunity "1"
-get5_kick_when_no_match_loaded "1"
3. Try to connect to passwordless server without aloaded matchconfig

Server was rebooted on every config change and SM admin was confirmed working by setting get_kick_when_no_match_loaded "0" and executing multiple SM admin commands. The get5.cfg is on all default values.

Debug (probably not very useful in this case)
```
L 04/16/2019 - 22:42:07: [get5] Event_RoundEnd
L 04/16/2019 - 22:42:07: [get5] Event_RoundPreStart
L 04/16/2019 - 22:42:13: [get5] Event_RoundEnd
L 04/16/2019 - 22:42:14: [get5] Event_RoundPreStart
L 04/16/2019 - 22:42:14: [get5] get5_event: {"matchid`":"","params":{"client":"none","map_number":0,"map_name":"de_mirage"},"event":"player_disconnect"}
L 04/16/2019 - 22:43:48: [get5] get5_event: {"matchid`":"","params":{"client":"none","map_number":0,"map_name":"de_mirage"},"event":"player_disconnect"}

```

**Comment by TandelK** [comment] 2019-04-19 07:28
Can you try to use once admins.cfg instead of admins_simple.ini and let me know if the error is still there.

**Comment by TandelK** [comment] 2019-05-08 19:02
@splewis I can confirm there is a issue with this. Even i tried replicating it and it doesnt work. Admins get message that there is no match setup .

**Comment by TheUdK** [comment] 2019-05-09 09:31
@TandelK same issue with admins.cfg. dont know it you tested both.

**Comment by TandelK** [comment] 2019-05-09 11:27
@TheUdK I tested it out and than only updated the above with tagging of splewis that there was a issue with this. I think this issue came after changing of values and integrating booleans

**Comment by TandelK** [comment] 2019-05-13 10:18
I even checked the code of it and it should be working fine but still even i have the same issue.

**Comment by TandelK** [comment] 2019-05-19 05:23
@splewis Can you look into this ? I tried replicating the same issue and it is there that even with Change Map flag Admin Flag no one is able to join the server with the above cvar

**Comment by TandelK** [comment] 2019-06-20 06:15
@TheUdK The basic function of kick immunity is to allow admins to join server when match is loaded and Admin is not added in Spectator list so without adding admins to spectators list all admins can join the server.

**Comment by TheUdK** [comment] 2019-06-20 11:03
@TandelK Im aware. But this does not work as i discribed in my report.

**Comment by TandelK** [comment] 2019-06-22 09:48
`Expected behavior
Allow admin to join on server with no match loaded.`


There is no match loaded so no one can join.

**Comment by TheUdK** [comment] 2019-06-24 08:42
@TandelK As described in my report there was no config loaded at the time of testing. The user was added as SM admin, was confirmed to be SM admin but was still not able to join the server with no get5 config loaded.

As i understand it, if get5_kick_immunity is set to 1 and get5_kick_when_no_match_loaded is also set to 1 then the SM admin (or an account with the changemap flag) should be able to join the server WITHOUT a  get5 match config file being loaded. Am i misinterpreting the comments for the ConVars?

`g_KickClientImmunity = CreateConVar(
      "get5_kick_immunity", "1",
      "Whether or not admins with the changemap flag will be immune to kicks from \"get5_kick_when_no_match_loaded\". Set to \"0\" to disable");
  g_KickClientsWithNoMatchCvar =
      CreateConVar("get5_kick_when_no_match_loaded", "1",
                   "Whether the plugin kicks new clients when no match is loaded");`

**Comment by TandelK** [comment] 2019-06-24 13:31
Yeah even i got confuse but after i went through the source code i found that if match is loaded and admins with change flag but not added in Spectator they should be allowed to join without adding them in Spectator mode

**Comment by TheUdK** [comment] 2019-06-24 13:35
so it is a bug and as i described it?

**Comment by splewis** [comment] 2019-07-06 23:24
The relevant code: https://github.com/splewis/get5/blob/849cf3c76f33869e0b6bdb21ea7fa9e1c9caea82/scripting/get5.sp#L530-L536

The intention is that `get5_kick_immunity 1` means someone marked as an admin will NOT be kicked on connection, even if `get5_kick_when_no_match_loaded 1` is set. If that isn't happening, it's a bug. I haven't tried to reproduce anything, though. Anecdotally, I've experienced immunity worked as intended in the past.

**Comment by TandelK** [comment] 2019-07-09 12:45
@splewis Yes than its a bug because it kicks admins if there is no match setup.

**Comment by TandelK** [comment] 2019-08-28 10:57
@splewis Can you have a look into this. The bug still exists.

**Comment by Cruze03** [comment] 2019-09-15 11:09
https://github.com/splewis/get5/pull/427

**Comment by splewis** [comment] 2019-09-18 19:28
Thanks for the PR, that should fix the problem here.

**Closed by splewis** 2019-09-18 19:28 UTC
Labels: unverified bug
