### ISSUE TITLE
Coachslot behavior when switching teams

### ISSUE THREAD

**Issue by ddb69** [splewis/get5#715] opened 2021-11-04 06:30 UTC
I## Expected behavior
After knife round the opponent decides to switch to other side (T or CT) and the coach remains in coach slot.

### Actual behavior
After knife round the opponent decides to switch to other side (T or CT) and the coach is kicked out of coach slot and finds himself un spectator mode.

### Steps to reproduce
- Start a match
- Execute knife round
- Decide to swap/switch sides as winner

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version: 0.8.0-dev+533 (same problem with latest stable and other versions)
- Sourcemod version: 1.10.0.6516
- Steps to reproduce (please be specific): Start a match, Execute knife round, Decide to swap/switch sides as winner

**Comment by Drarig29** [comment] 2021-11-04 14:29
Duplicate of #471

**Closed** 2021-12-31 23:52 UTC
