### ISSUE TITLE
[not ready] tags are not removing when restoring match from backup

### ISSUE THREAD

**Issue by nikitosoz8** [splewis/get5#663] opened 2021-04-28 08:17 UTC
### Expected behavior

No [ready] tags in team names 

### Actual behavior

[ready] tags in team names appearing

### Steps to reproduce

Load match cfg, play some rounds, restart server, load backup. 

- Plugin version: 0.7.2-dev+524
- Sourcemod version: 1.10.0.6502

**Comment by splewis** [comment] 2021-06-28 04:04
Duplicate of https://github.com/splewis/get5/issues/163; PRs welcome!

**Closed by splewis** 2021-06-28 04:04 UTC
