### ISSUE TITLE
Map Veto

### ISSUE THREAD

**Issue by realRapSi** [splewis/get5#635] opened 2021-02-24 09:53 UTC
Hey splewis, just a quick question.
Is there a way to change the map veto order in the Best-of-Two system? We are running a different scheme and would need to change it.
Thanks and have a nice day

**Comment by splewis** [comment] 2021-02-25 02:07
It's not configurable. Only the format at https://github.com/splewis/get5/wiki/Map-Vetoes#bo2-veto is supported.

What order do you want? It might be easy enough to add a config option to allow it.

**Comment by realRapSi** [comment] 2021-02-25 06:59
new order would be: Team 1 bans 1 map, Team 2 bans 2 maps, Team 1 bans 1 map, Team 2 picks 1. map and Team 1 picks 2nd map. 
Basically A-B-B-A bans and B-A picks.

**Comment by lehmanner** [comment] 2021-03-29 18:53
That'd actually be great :D  aaaaand hi @realRapSi ;)

**Comment by nickdnk** [comment] 2022-07-11 14:32
Duplicate of https://github.com/splewis/get5/issues/643

**Closed by nickdnk** 2022-07-11 14:32 UTC
Labels: user help
