### ISSUE TITLE
Server stopped after 1 map in bo3 match (new update panorama)

### ISSUE THREAD

**Issue by Shivam16a** [splewis/get5#277] opened 2018-07-12 15:17 UTC
we had a match going on with b03 settings and server stopped like a bo1 match after 1st map completion everyone dropped although its was giving text in chat that next map will load after gotv broadcast finishes.

also, a new thing which I saw is the vote for next map on 1st map finish (i was using panorama) and other peoples who were not using panorama didn't saw any vote for next map. I have been using get5 for almost a year now never seen next map veto before.

Mentioning again its first time I ran get5 server after official panorama update.
if I have done any settings wrong please tell me or dev can look in case update broken the plugin.

0.6.0- Plugin version
SourceMod Version: 1.8.0.6046
SourcePawn Engine: SourcePawn 1.8, jit-x86 (build 1.8.0.6046)

[match_305.cfg.txt](https://github.com/splewis/get5/files/2189187/match_305.cfg.txt)

**Comment by Technoblazed** [comment] 2018-07-12 15:19
Probably not the cause of the issue, but you need to use Sourcemod 1.9 (6241 and later), any older versions no longer works for CS:GO.

**Comment by Shivam16a** [comment] 2018-07-12 15:25
ok Updating the sourcemode will post back if issue stays thanks for the quick reply,
but any idea what can cause the issue rather than this old sourcemode bcoz server was fine and the plugin was also working as it should until map finished.

* i will pull the logs out once ongoing match finishes had to start the match in old way

**Comment by splewis** [comment] 2018-07-14 03:50
I'm closing this since I don't think you're seeing a get5 bug. If you still have issues after updating a 1.9 build of sourcemod please make a new issue with clearer description of the problem.

**Closed by splewis** 2018-07-14 03:50 UTC
