### ISSUE TITLE
get5_web_avaliable command fails

### ISSUE THREAD

**Issue by makhoder** [splewis/get5#321] opened 2018-11-21 13:03 UTC
I did all the steps and I am being able to run the website.
But when I put get5_web_avaliable on console, i get the following output (steamworks is installed and it is showing in meta list)
L 11/21/2018 - 14:39:41: [SM] Exception reported: Instruction contained invalid parameter
L 11/21/2018 - 14:39:41: [SM] Blaming: get5_apistats.smx
L 11/21/2018 - 14:39:41: [SM] Call stack trace:
L 11/21/2018 - 14:39:41: [SM]   [1] Line 165, /var/lib/jenkins/workspace/get5/tmp/addons/sourcemod/scripting/include/json.inc::json_encode
L 11/21/2018 - 14:39:41: [SM]   [2] Line 696, /var/lib/jenkins/workspace/get5/tmp/addons/sourcemod/scripting/include/json/object.inc::JSON_Object.Encode
L 11/21/2018 - 14:39:41: [SM]   [3] Line 90, ./scripting/get5_apistats.sp::Command_Avaliable

**Comment by splewis** [comment] 2018-11-22 03:30
Version numbers?

https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version

**Comment by makhoder** [comment] 2018-11-22 03:31
Newest version v448

**Comment by splewis** [comment] 2018-11-22 03:34
Can you check your sourcemod version as well? 

https://github.com/splewis/get5/wiki/Debugging-help#finding-sourcemod-version

Some quick searching indicates this may be an out-of-date sourcmeod or out-of-date SteamWorks installation.

**Comment by makhoder** [comment] 2018-11-22 03:35
sourcemod v6261, newest one here https://www.sourcemod.net/downloads.php (get5 plugin is working normally)

**Comment by splewis** [comment] 2018-11-22 04:31
Can you post the actual output from ``sm version`` and ``sm exts list``?

**Comment by makhoder** [comment] 2018-11-22 04:32
06:32:14: rcon@127.0.1.1:27017> sm version
 SourceMod Version Information:
    SourceMod Version: 1.10.0.6356
    SourcePawn Engine: 1.10.0.6356, jit-x86 (build 1.10.0.6356)
    SourcePawn API: v1 = 4, v2 = 12
    Compiled on: Nov 13 2018 08:33:37
    Built from: https://github.com/alliedmodders/sourcemod/commit/f0aec6b
    Build ID: 6356:f0aec6b
    http://www.sourcemod.net/
   

06:32:28: rcon@127.0.1.1:27017> sm exts list
[SM] Displaying 11 extensions:
[01] Automatic Updater (1.10.0.6356): Updates SourceMod gamedata files
[02] Webternet (1.10.0.6356): Extension for interacting with URLs
[03] <FAILED> file "cleaner.ext.2.csgo.so": Failed to find signature. Please contact the author.
[04] SMJansson (2.3.1/3): JSON parser/writer
[05] CS Tools (1.10.0.6356): CS extended functionality
[06] BinTools (1.10.0.6356): Low-level C/C++ Calling API
[07] SDK Tools (1.10.0.6356): Source SDK Tools
[08] Top Menus (1.10.0.6356): Creates sorted nested menus
[09] SteamWorks Extension (1.2.3): Exposes SteamWorks functions to Developers
[10] Client Preferences (1.10.0.6356): Saves client preference settings
[11] SQLite (1.10.0.6356): SQLite Driver

**Comment by splewis** [comment] 2018-11-22 23:15
Hm, I'm able to reproduce this easily. It seems like it's been happening since https://github.com/splewis/get5/commit/c44966f2db6ccfa45172ee72ac5e5302b43ff2bb.

Not clear if it's a issue with the plugin itself, how it's being compiled, or the version of SM running. (the user here has a SM 1.10 version, but I'm running into it on sm-1.9.6241).

**Comment by makhoder** [comment] 2018-11-23 08:50
After downgrading get5-web plugin to 0.6.0 I was able to get this output.

10:49:32: rcon@127.0.1.1:27017> get5_web_available
{
    "plugin_version": "0.7.0-dev+448",
    "gamestate": 0,
    "avaliable": 1
}

After trying to create a match, I get this output.
L 11/23/2018 - 10:39:49: [get5.smx] Failed to load match config: Steamworks GET request failed, HTTP status code = 0

**Comment by splewis** [comment] 2018-11-23 09:06
There's not much I can do to help you debug that. 

Users will get that if they didn't host the webpanel on an actual domain name (rather than a ip:port), see https://github.com/splewis/get5-web/blob/master/INSTALL.md#10-webserver-configuration.

**Comment by splewis** [comment] 2018-11-30 05:57
Closing since there's no update here.

**Closed by splewis** 2018-11-30 05:57 UTC
Labels: user help
