### ISSUE TITLE
[FR] Don't changelevel when map matches

### ISSUE THREAD

**Issue by kubo6472** [splewis/get5#746] opened 2022-03-01 21:46 UTC
After veto if for some reason the map matches the map being played, do not changelevel. Or is it better to do so anyway?

**Comment by deLuXe83** [comment] 2022-03-04 07:43
yes, i experienced this behaviour as well...

**Comment by PhlexPlexico** [comment] 2022-05-23 19:37
Looks like this may not be required, and the change would take place in the `Timer_NextMatchMap` function since it calls a timer for it. However, I'm unsure if there are going to be any handles that may cause issues with this, especially with GoTV running - 

https://github.com/splewis/get5/blob/5afc25b5f27e2bae923c2e47e3cfbc901259bbc6/scripting/get5.sp#L1089-L1103

There could be a simple change made that can just check if the current map is the picked map, but I think some significant testing would have to be done with the vetoes to check this. If you have some time, I could spin up a branch and a few test cases as well to ensure everything works as intended?

**Comment by PhlexPlexico** [comment] 2022-07-08 20:19
Was talking with @nickdnk about this the other day. I think it's best if we leave this in actually since there may be some hanging variables/stuff that is set by the game server that needs to be reset. It's best to start on a clean slate after the veto calls, so we can ensure that everything will work as intended. So I think we may mark this one as a wontfix.

**Closed** 2022-07-10 08:36 UTC
Labels: won't-fix
