### ISSUE TITLE
 problem that backup

### ISSUE THREAD

**Issue by 1lover** [splewis/get5#583] opened 2020-10-10 14:37 UTC
Hey!

I have the problem that backup are just restarting match to score 0-0. What do I need to do to fix it?

**Comment by splewis** [comment] 2020-12-04 02:38
I don't know. If you can reproduce it, steps to do that  would help, like the template asks for:
```
If making a feature request, you should delete all the pre-filled text here.
If reporting a bug, fill in the following sections:

### Expected behavior



### Actual behavior



### Steps to reproduce

Please note that "latest" is NOT a version! See https://github.com/splewis/get5/wiki/Debugging-help#finding-get5-version if you need help finding these. Adding the output file produced by ``get5_debuginfo`` is extremely helpful.

- Plugin version:
- Sourcemod version:
- Steps to reproduce (please be specific):

```

**Comment by nickdnk** [comment] 2021-12-31 23:56
Likely a duplicate of https://github.com/splewis/get5/issues/287.

**Closed by nickdnk** 2021-12-31 23:56 UTC
Labels: user help
