### ISSUE TITLE
Remote configuration doesn't load right after server start. 

### ISSUE THREAD

**Issue by jfkz** [splewis/get5#55] opened 2016-08-28 10:10 UTC
I found strange behaviour when I tested plugin with remote controlled matches. 

If we send get5_loadmatch_url _url_ right after server started it does nothing. 

If we started any other match (get5_scrim or get5_liadmatch), then finished it get5_loadmatch_url works perfect. 

Have no time to found where is the problem so need some help.

**Comment by splewis** [comment] 2016-08-28 19:36
It might need a check for ``SteamWorks_IsLoaded`` before attempting to send requests.

**Comment by jfkz** [comment] 2016-08-28 20:05
Got it. Can we do it in get5_loadmatch_url method?

**Comment by jfkz** [comment] 2016-08-30 23:45
I investigated this problem and found a solution for system2 (SteamWorks crashes on my server): https://github.com/jfkz/get5/commit/b3bd03105f95b78649c9edd523bb66a75af06db1#diff-ccf8a04d07fd0839c118dfb2d59814a6R187

It looks like magic, but it works absolutelly correct at any cases (load match right after server load or after some matches).

**Comment by splewis** [comment] 2016-08-31 15:30
I haven't looked into this, but I'd like to actually know what the issue is before I would make that change.

All of my testing has used SteamWorks generally. Does this only happen with System2 as far as you know?

**Comment by jfkz** [comment] 2016-08-31 20:47
Probably yes. 

I can't use steamworks cause it crashes each time on my server.

**Comment by morpig** [comment] 2016-11-11 11:29
same. for me, the match JSON is downloaded after after a player joining a server. I think system2 dont work when server is hibernating.

**Comment by Technoblazed** [comment] 2016-11-11 11:58
Then set your server to not hibernate? Isn't that pretty obvious?

**Comment by morpig** [comment] 2016-11-11 12:03
@Technoblazed what's the command? I tried sv_hibernate_when_empty, even from the srcds (./srcds_run -sv_hibernate_when_empty 0), still not working.

**Comment by Technoblazed** [comment] 2016-11-11 12:07
sv_hibernate_when_empty 0
sv_hibernate_postgame_delay 0
In your server.cfg

**Comment by Technoblazed** [comment] 2016-11-11 12:08
Your other option is to change a line in the plugin and allow admins to join before a match is live

**Comment by jfkz** [comment] 2016-11-11 12:48
Guys, take a look at my previous messages - I found simple way to solve this issue that is working now.

**Comment by morpig** [comment] 2016-11-11 13:36
@splewis I tried to compile @jfkz  code, and from my observation, he's adding execwarmup because it runs commands, and the server is out of hibernating mode.

**Comment by jfkz** [comment] 2016-11-11 13:47
@morpig
Yeah, that's right.

**Comment by splewis** [comment] 2018-05-13 05:29
Closing since there's not really a clear bug here.

**Closed by splewis** 2018-05-13 05:29 UTC
